"""Add many-to-many relationship for tasks and users

Revision ID: 4fe146ee768a
Revises: 5b3de49e9a58
Create Date: 2024-10-10 15:02:48.383169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe146ee768a'
down_revision = '5b3de49e9a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_category_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        # Remove the drop_constraint line below, as it may not exist
        # batch_op.drop_constraint('fk_task_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_task_category_id', 'category', ['category_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_task_category_id', type_='foreignkey')
        # Remove the create_foreign_key line below, as it may not be needed
        # batch_op.create_foreign_key('fk_task_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('category_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
