"""Add category_id to ActivityLog

Revision ID: a5f7afe8834b
Revises: b64723ccf546
Create Date: 2024-10-14 15:45:23.277613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f7afe8834b'
down_revision = 'b64723ccf546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # Add a name to the foreign key constraint
        batch_op.create_foreign_key('fk_activity_log_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        # Drop the constraint by its name
        batch_op.drop_constraint('fk_activity_log_category_id', type_='foreignkey')
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
