"""Initial migration again

Revision ID: b2e021cdd02f
Revises: 
Create Date: 2024-10-26 18:01:41.522540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e021cdd02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_task')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('purpose')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')

with op.batch_alter_table('task_invitation', schema=None) as batch_op:
    batch_op.add_column(sa.Column('date_sent', sa.DateTime(), nullable=False, server_default=sa.func.now()))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_invitation', schema=None) as batch_op:
        batch_op.drop_column('date_sent')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=50), server_default=sa.text("'Medium'"), nullable=False))
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=255), nullable=True))

    op.create_table('_alembic_tmp_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
