"""Add category_user table

Revision ID: d404745fe6d8
Revises: b1e0d10a867d
Create Date: 2024-10-27 14:50:34.396795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd404745fe6d8'
down_revision = 'b1e0d10a867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
